# Maintainer: Vagelis Fragkos (xneo1)
# Update: 2022-08-02

#& type: 3
#& title: Aria2Pro
#& description: A perfect Aria2 Docker image. Out of the box, just add download tasks and don't need to think about anything else.
#& note: Website: <a href='https://github.com/P3TERX/Aria2-Pro-Core/blob/master/README.md' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, Downloading, xneo1
#& platform: linux
#& logo: https://seeklogo.com/images/A/Aria_Pro_II-logo-6937ED8402-seeklogo.com.png

#% SERVICE: Name of the service (No spaces or points) [aria2-pro]
#% DATA_LOCATION: Data location (Example: /apps/service) [/portainer/Files/AppData/Config/]
#% URL: Service URL (Example: service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer

version: "2.0"
services:
  aria2pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      #- RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Europe/Athens
    volumes:
      - $DATA_LOCATION/$SERVICE: /config
      - $DATA_LOCATION/$SERVICE/Downloads: /downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
#    network_mode: host
    network_mode: bridge
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: always
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    environment:
      - PUID=1000
      - PGID=1000
      - ARIA2RPCPORT=6800
      - RPC_SECRET=P3TERX
    command: --port 6880 --ipv6
#    network_mode: host
    network_mode: bridge
    ports:
      - 6880:6880
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m

networks:
  default:
    external:
      name: $NETWORK
