# Maintainer: Vagelis Fragkos (xneo1)
# Update: 2022-08-02

#& type: 3
#& title: broadlinkmanager
#& description: BroadlinkManager is a Flask powered, easy to use system that hepls you to work with Broadlink Devices.
#& note: Website: <a href='https://hub.docker.com/r/techblog/broadlinkmanager' target='_blank' rel='noopener'>Broadlink-manager</a>
#& categories: SelfHosted, Smart Home, xneo1
#& platform: linux
#& logo: https://raw.githubusercontent.com/xneo1/portainer_templates/master/Images/broadlink.png

#% SERVICE: Name of the service (No spaces or points) [broadlinkmanager]
#% DATA_LOCATION: Data location (Example: /apps/service) [/portainer/Files/AppData/Config/]
#% URL: Service URL (Example: service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "2"
services:
  # Hastebin : https://hub.docker.com/r/techblog/broadlinkmanager
  broadlinkmanager:
    image: techblog/broadlinkmanager
    container_name: $SERVICE
    restart: unless-stopped
    environment:
      STORAGE_TYPE: file
    volumes:
      - $DATA_LOCATION/$SERVICE:/data
    healthcheck:
      test: wget -s 'http://localhost:7020'
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/xneo1/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK
