# Maintainer: Vagelis Fragkos (xneo1)
# Update: 2022-08-02

#& type: 3
#& title: Dashy
#& description: Helps you organize your self-hosted services by making them accessible from a single place.
#& note: Website: <a href='https://dashy.to/' target='_blank' rel='noopener'>Dashy.to</a>
#& categories: SelfHosted, Dashboard, xneo1
#& platform: linux
#& logo: https://dashy.to/img/dashy.png

#% SERVICE: Name of the service (No spaces or points) [dashy]
#% DATA_LOCATION: Data location (Example: /apps/service) [/portainer/Files/AppData/Config]
#% URL: Service URL (Example: service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: $SERVICE
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - $DATA_LOCATION/$SERVICE/conf.yml:/app/public/conf.yml
      - $DATA_LOCATION/$SERVICE/icons:/app/public/item-icons/icons
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/xneo1/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK
