# Maintainer: Vagelis Fragkos (xneo1)
# Update: 2022-08-03

#& type: 3
#& title: jump
#& description: Jump is yet another self-hosted startpage for your server designed to be simple, stylish, fast and secure.
#& note: Website: <a href='https://github.com/daledavies/jump/blob/main/README.md' target='_blank' rel='noopener'>Jump</a>
#& categories: SelfHosted, Dashboard, xneo1
#& platform: linux
#& logo: https://github.com/daledavies/jump/raw/main/screenshots/screenshot-demo.webp

#% SERVICE: Name of the service (No spaces or points) [jump]
#% DATA_LOCATION: Data location (Example: /apps/service) [/portainer/Files/AppData/Config]
#% URL: Service URL (Example: service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "2"
services:
  # Jump : https://github.com/daledavies/jump/blob/main/README.md
  jump:
    image: daledavies/jump
    container_name: $SERVICE
    restart: always
    environment:
      STORAGE_TYPE: file
    volumes:
      - $DATA_LOCATION/$SERVICE/backgrounds:/backgrounds
      - $DATA_LOCATION/$SERVICE/favicon:/favicon
      - $DATA_LOCATION/$SERVICE/search:/search
      - $DATA_LOCATION/$SERVICE/sites:/sites

    healthcheck:
      test: wget -s 'http://localhost:9123'
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/xneo1/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK
