# Maintainer: Vagelis Fragkos (xneo1)
# Update: 2022-09-26


#& type: 3
#& title: OpenBudgeteer
#& description: OpenBudgeteer is a budgeting app based on the Bucket Budgeting Principle and inspired by YNAB and Buckets.
#& note: Website: <a href='https://github.com/TheAxelander/OpenBudgeteer' target='_blank' rel='noopener'>OpenBudgeteer</a>
#& categories: Finance, xneo1
#& platform: linux
#& logo: https://github.com/TheAxelander/OpenBudgeteer/raw/master/assets/banner.png?raw=true

#% SERVICE: Name of the service (No spaces or points) [OpenBudgeteer]
#% URL: Service URL (Example: service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "3"
services:
  openbudgeteer:
    image: axelander/openbudgeteer
    ports:
      - 8081:80
    restart: always
    container_name: $SERVICE
    environment:
      - Connection:Server=openbudgeteer-mysql
      - Connection:Port=3306
      - Connection:Database=openbudgeteer
      - Connection:User=openbudgeteer
      - Connection:Password=openbudgeteer
      - AppSettings:Culture=en-US
    depends_on:
      - openbudgeteermysql
    networks:
      - app-global
      - ob-mysql-internal
    healthcheck:
      test: curl --fail http://localhost:8081|| exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/xneo1/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=8081"
      - "traefik.docker.network=$NETWORK"
  openbudgeteermysql:
    image: mysql
    container_name: openbudgeteer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword
    volumes:
      - /portainer/Files/AppData/Config/openbudgeteer/data:/var/lib/mysql
    networks:
      - ob-mysql-internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: openbudgeteer-phpmyadmin
    links:
      - openbudgeteermysql:db
    ports:
      - 8080:80
    networks:
      - app-global
      - ob-mysql-internal 	  	  
networks:
  default:
    external:
      name: $NETWORK
