name: pull_request
on:
  pull_request:
    branches:
    - master
  workflow_dispatch:
jobs:
  check-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.1
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint --format github -d .github/workflows/conf_yaml ./composes-files/*
