name: master
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  check-yaml:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint --format github -d .github/workflows/conf_yaml ./composes-files/*
  generate-files:
    needs: check-yaml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Generate json file
        run: python3 .github/workflows/generate-template-json.py
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automatic generation of the file templates-portainer.json"
          git push
